name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # 可选: 允许读取 pull request。与 'only-new-issues' 选项一起使用。
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # 必须指定版本
          version: v1.60
          # 可选: 显示仅新发现的问题
          only-new-issues: true
